#!/usr/bin/env python3
"""Fast outer CEGIS search for the prescribed-colour factor gate.

This model retains:

* exactly 27 deleted edges and deleted degrees between one and five;
* the exact seven-triple/four-five-set remaining-row ledger;
* every internal-edge capacity cut (C); and
* an explicit edge-disjoint perfect-matching witness for each selected
  pair of supports.

It deliberately omits only the requirement that the 27 deleted edges split
into prefix matchings of sizes 4,4,4,5,5,5.  Thus UNSAT is a valid theorem
for the full target, while SAT is only a relaxed obstruction candidate.

No-three clauses are generated by CEGIS.  An UNSAT result is not promoted
until the emitted CNF receives an external proof trace and semantic audit.
"""

from __future__ import annotations

import argparse
import json
import time
from itertools import combinations
from pathlib import Path

from pysat.solvers import Cadical195

import freeze_full_row_cut_sufficiency as freeze
import search_counterexamples as search


PAIR_INDICES = tuple(combinations(range(3), 2))


def build_outer_instance(
    omitted_triples: tuple[tuple[int, ...], ...],
) -> tuple[search.Cnf, int]:
    cnf = search.Cnf()
    triple_sets = tuple(frozenset(triple) for triple in omitted_triples)
    supports = tuple(frozenset(search.VERTICES) - row for row in triple_sets)

    def deleted(edge_index: int) -> int:
        return cnf.variable(("deleted_edge", edge_index))

    def remaining_row(row: int, vertex: int) -> int:
        return cnf.variable(("remaining_row", row, vertex))

    # The deleted graph is a sound relaxation of the six prefix layers.
    cnf.cardinality(
        ("deleted_total",),
        [deleted(edge_index) for edge_index in range(len(search.EDGES))],
        lower=sum(search.PREFIX_SIZES),
        upper=sum(search.PREFIX_SIZES),
    )
    for vertex in search.VERTICES:
        cnf.cardinality(
            ("deleted_degree", vertex),
            [
                deleted(edge_index)
                for edge_index, edge in enumerate(search.EDGES)
                if vertex in edge
            ],
            lower=1,
            upper=5,
        )

    # Safe D-vector symmetry within every fixed selected-row Venn cell.
    membership_cells: dict[tuple[bool, ...], list[int]] = {}
    for vertex in search.VERTICES:
        pattern = tuple(vertex in row for row in triple_sets)
        membership_cells.setdefault(pattern, []).append(vertex)
    deleted_vector = [
        deleted(edge_index) for edge_index in range(len(search.EDGES))
    ]
    for cell_index, cell in enumerate(
        sorted(
            membership_cells.values(),
            key=lambda vertices: tuple(vertices),
        )
    ):
        for swap_index, (left_vertex, right_vertex) in enumerate(
            zip(cell, cell[1:])
        ):

            def swapped(vertex: int) -> int:
                if vertex == left_vertex:
                    return right_vertex
                if vertex == right_vertex:
                    return left_vertex
                return vertex

            swapped_vector = [
                deleted(
                    search.EDGE_INDEX[
                        tuple(
                            sorted(
                                (swapped(edge[0]), swapped(edge[1]))
                            )
                        )
                    ]
                )
                for edge in search.EDGES
            ]
            search.lexicographic_leq(
                cnf,
                ("deleted_vertex_swap", cell_index, swap_index),
                deleted_vector,
                swapped_vector,
            )

    # Exact full remaining-row inventory.
    remaining_sizes = (3,) * 7 + (5,) * 4
    for row, size in enumerate(remaining_sizes):
        cnf.cardinality(
            ("remaining_row_size", row),
            [remaining_row(row, vertex) for vertex in search.VERTICES],
            lower=size,
            upper=size,
        )
    for row, triple in enumerate(triple_sets):
        for vertex in search.VERTICES:
            literal = remaining_row(row, vertex)
            cnf.add(literal if vertex in triple else -literal)
    for left, right in (
        (3, 4),
        (4, 5),
        (5, 6),
        (7, 8),
        (8, 9),
        (9, 10),
    ):
        search.lexicographic_leq(
            cnf,
            ("remaining_row", left, right),
            [remaining_row(left, vertex) for vertex in search.VERTICES],
            [remaining_row(right, vertex) for vertex in search.VERTICES],
        )
    for vertex in search.VERTICES:
        cnf.cardinality(
            ("class_b_column", vertex),
            [
                deleted(edge_index)
                for edge_index, edge in enumerate(search.EDGES)
                if vertex in edge
            ]
            + [
                -remaining_row(row, vertex)
                for row in range(len(remaining_sizes))
            ],
            lower=12,
            upper=12,
        )

    # Install all capacity cuts statically.
    capacity_cuts = 0
    for vertices, internal_edges, required in search.cut_requirements(
        omitted_triples
    ):
        maximum_deleted = min(
            len(internal_edges),
            5 * len(vertices) // 2,
            sum(search.PREFIX_SIZES),
        )
        if required <= len(internal_edges) - maximum_deleted:
            continue
        cnf.cardinality(
            ("cut_feasible", vertices),
            [-deleted(edge_index) for edge_index in internal_edges],
            lower=required,
        )
        capacity_cuts += 1

    # Pairwise compatibility is encoded directly, without using the pair
    # classification theorem.  Each pair gets its own existential matchings.
    for pair_index, pair in enumerate(PAIR_INDICES):
        for family in pair:
            support = supports[family]
            for edge_index, edge in enumerate(search.EDGES):
                if edge[0] not in support or edge[1] not in support:
                    continue
                literal = cnf.variable(
                    ("pair_edge", pair_index, family, edge_index)
                )
                cnf.add(-literal, -deleted(edge_index))
            for vertex in sorted(support):
                incident = [
                    cnf.variable(
                        ("pair_edge", pair_index, family, edge_index)
                    )
                    for edge_index, edge in enumerate(search.EDGES)
                    if vertex in edge
                    and edge[0] in support
                    and edge[1] in support
                ]
                cnf.cardinality(
                    ("pair_vertex", pair_index, family, vertex),
                    incident,
                    lower=1,
                    upper=1,
                )
        left, right = pair
        common = supports[left] & supports[right]
        for edge in combinations(sorted(common), 2):
            edge_index = search.EDGE_INDEX[edge]
            cnf.cardinality(
                ("pair_edge_capacity", pair_index, edge),
                [
                    cnf.variable(
                        ("pair_edge", pair_index, left, edge_index)
                    ),
                    cnf.variable(
                        ("pair_edge", pair_index, right, edge_index)
                    ),
                ],
                upper=1,
            )

    return cnf, capacity_cuts


def verify_relaxed_candidate(
    cnf: search.Cnf,
    omitted_triples: tuple[tuple[int, ...], ...],
    model: frozenset[int],
) -> dict[str, object]:
    deleted = tuple(
        edge_index
        for edge_index in range(len(search.EDGES))
        if cnf.variable(("deleted_edge", edge_index)) in model
    )
    deleted_set = frozenset(deleted)
    deleted_mask = sum(1 << edge_index for edge_index in deleted)
    assert len(deleted) == 27
    assert all(
        1
        <= sum(
            edge_index in deleted_set
            for edge_index, edge in enumerate(search.EDGES)
            if vertex in edge
        )
        <= 5
        for vertex in search.VERTICES
    )
    assert search.violated_cut(
        search.cut_requirements(omitted_triples),
        deleted_mask,
    ) is None

    rows = [
        [
            vertex
            for vertex in search.VERTICES
            if cnf.variable(("remaining_row", row, vertex)) in model
        ]
        for row in range(11)
    ]
    assert tuple(tuple(row) for row in rows[:3]) == omitted_triples
    assert [len(row) for row in rows] == [3] * 7 + [5] * 4
    for vertex in search.VERTICES:
        degree = sum(
            edge_index in deleted_set
            for edge_index, edge in enumerate(search.EDGES)
            if vertex in edge
        )
        incidence = sum(vertex in row for row in rows)
        assert incidence == degree - 1

    pair_witnesses = []
    triple_sets = tuple(frozenset(row) for row in omitted_triples)
    supports = tuple(
        frozenset(search.VERTICES) - row for row in triple_sets
    )
    for pair_index, pair in enumerate(PAIR_INDICES):
        pair_edges = []
        used: set[int] = set()
        for family in pair:
            chosen = tuple(
                edge_index
                for edge_index, edge in enumerate(search.EDGES)
                if edge[0] in supports[family]
                and edge[1] in supports[family]
                and cnf.variable(
                    ("pair_edge", pair_index, family, edge_index)
                )
                in model
            )
            assert len(chosen) == 5
            assert deleted_set.isdisjoint(chosen)
            assert used.isdisjoint(chosen)
            used.update(chosen)
            pair_edges.append([search.EDGES[index] for index in chosen])
        pair_witnesses.append(pair_edges)

    return {
        "deleted_edges": [search.EDGES[index] for index in deleted],
        "remaining_complements": rows,
        "pair_witnesses": pair_witnesses,
    }


def solve_orbit(
    orbit_index: int,
    signature: tuple[int, ...],
    omitted_triples: tuple[tuple[int, ...], ...],
    *,
    cut_batch: int,
    max_rounds: int,
    cnf_dir: Path,
) -> dict[str, object]:
    start = time.monotonic()
    cnf, capacity_cuts = build_outer_instance(omitted_triples)
    families = tuple(
        search.perfect_matchings(
            tuple(
                sorted(
                    frozenset(search.VERTICES) - frozenset(triple)
                )
            )
        )
        for triple in omitted_triples
    )
    masks = search.matching_masks(families)
    learned_unions: set[tuple[int, ...]] = set()
    rounds = 0
    initial_clauses = len(cnf.clauses)
    solver = Cadical195(bootstrap_with=cnf.clauses)
    try:
        while max_rounds == 0 or rounds < max_rounds:
            rounds += 1
            if not solver.solve():
                cnf_path = cnf_dir / f"orbit_{orbit_index}.cnf"
                result: dict[str, object] = {
                    "status": "unsat",
                    "cnf_path": str(cnf_path),
                    "cnf_sha256": search.write_dimacs(cnf_path, cnf),
                }
                break
            model = frozenset(
                literal for literal in solver.get_model() if literal > 0
            )
            deleted_mask = sum(
                1 << edge_index
                for edge_index in range(len(search.EDGES))
                if cnf.variable(("deleted_edge", edge_index)) in model
            )
            available = search.available_indices(masks, deleted_mask)
            new_unions: set[tuple[int, ...]] = set()
            for matching_indices in search.disjoint_triples(
                masks,
                available,
                cut_batch,
            ):
                union = tuple(
                    sorted(
                        {
                            edge_index
                            for family, matching_index in enumerate(
                                matching_indices
                            )
                            for edge_index in families[family][matching_index]
                        }
                    )
                )
                if len(union) != 15:
                    raise AssertionError("matching triple is not edge-disjoint")
                if union not in learned_unions:
                    new_unions.add(union)
            if not new_unions:
                details = verify_relaxed_candidate(
                    cnf,
                    omitted_triples,
                    model,
                )
                result = {
                    "status": "relaxed-counterexample",
                    **details,
                }
                break
            for union in sorted(new_unions):
                clause = tuple(
                    cnf.variable(("deleted_edge", edge_index))
                    for edge_index in union
                )
                cnf.add(*clause)
                solver.add_clause(clause)
            learned_unions.update(new_unions)
        else:
            result = {"status": "round-limit"}
    finally:
        solver.delete()

    result.update(
        {
            "orbit": orbit_index,
            "signature": signature,
            "omitted_triples": omitted_triples,
            "rounds": rounds,
            "learned_unions": len(learned_unions),
            "variables": cnf.top,
            "initial_clauses": initial_clauses,
            "final_clauses": len(cnf.clauses),
            "capacity_cuts": capacity_cuts,
            "elapsed_seconds": round(time.monotonic() - start, 3),
            "decision_scope": (
                "full-row cut-feasible pairwise-compatible outer model; "
                "prefix-layer decomposition omitted"
            ),
            "proof_claimed": False,
        }
    )
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--orbits", default="all")
    parser.add_argument("--cut-batch", type=int, default=10_000)
    parser.add_argument("--max-rounds", type=int, default=0)
    parser.add_argument("--cnf-dir", type=Path, required=True)
    parser.add_argument("--jsonl", type=Path)
    args = parser.parse_args()
    if args.cut_batch <= 0:
        parser.error("--cut-batch must be positive")
    if args.max_rounds < 0:
        parser.error("--max-rounds must be nonnegative")

    orbits = freeze.support_orbits_fast()
    selected = search.parse_orbits(args.orbits, len(orbits))
    output = args.jsonl.open("a", encoding="utf-8") if args.jsonl else None
    try:
        for orbit_index in selected:
            signature, representative = orbits[orbit_index]
            result = solve_orbit(
                orbit_index,
                signature,
                representative,
                cut_batch=args.cut_batch,
                max_rounds=args.max_rounds,
                cnf_dir=args.cnf_dir,
            )
            line = json.dumps(result, sort_keys=True)
            print(line, flush=True)
            if output:
                output.write(line + "\n")
                output.flush()
            if result["status"] == "relaxed-counterexample":
                break
    finally:
        if output:
            output.close()


if __name__ == "__main__":
    main()
