#!/usr/bin/env python3
"""Exact exploratory checks for the point-incidence code of S(14,15,31).

This is an obstruction search, not an existence proof.  It derives the
forced weight distribution of the binary code generated by the 31 point
rows of a hypothetical S(14,15,31), checks initial MacWilliams
coefficients, and tests Griesmer bounds before and after shortening by
small binary simplex subcodes.
"""

from __future__ import annotations

from collections import Counter
from math import comb


V = 31
K = 15
T = 14
DIMENSION = 31
BLOCKS = comb(V, T) // K


def parameters() -> tuple[int, ...]:
    return tuple(
        comb(V - level, T - level) // (K - level)
        for level in range(T + 1)
    )


LAMBDA = parameters()


def fourier_value(size: int, internal_middle: bool = False) -> int:
    """Return sum_B (-1)^|B cap S| for a set S of the given size."""
    if size > V // 2:
        # Every block has odd size.
        return -fourier_value(V - size, internal_middle)
    answer = sum(
        (-2) ** level * comb(size, level) * LAMBDA[level]
        for level in range(min(size, T) + 1)
    )
    if size == K and internal_middle:
        answer += (-2) ** K
    return answer


def code_weight(size: int, internal_middle: bool = False) -> int:
    return (BLOCKS - fourier_value(size, internal_middle)) // 2


def forced_weight_distribution() -> Counter[int]:
    distribution: Counter[int] = Counter()
    for size in range(T + 1):
        weight = code_weight(size)
        multiplicity = comb(V, size)
        distribution[weight] += multiplicity
        distribution[BLOCKS - weight] += multiplicity

    internal = code_weight(K, True)
    external = code_weight(K, False)
    middle_count = comb(V, K)
    distribution[internal] += BLOCKS
    distribution[external] += middle_count - BLOCKS
    distribution[BLOCKS - internal] += BLOCKS
    distribution[BLOCKS - external] += middle_count - BLOCKS
    assert sum(distribution.values()) == 1 << DIMENSION
    return distribution


def krawtchouk_coefficients(
    distribution: Counter[int], maximum_degree: int
) -> list[int]:
    rows = {
        weight: [1, BLOCKS - 2 * weight]
        for weight in distribution
    }
    denominator = 1 << DIMENSION
    answer = [1]
    for degree in range(1, maximum_degree + 1):
        coefficient = sum(
            distribution[weight] * rows[weight][1]
            for weight in rows
        )
        assert coefficient % denominator == 0
        coefficient //= denominator
        assert coefficient >= 0
        answer.append(coefficient)
        if degree == maximum_degree:
            break
        for weight, values in rows.items():
            previous, current = values
            following = (
                (BLOCKS - 2 * weight) * current
                - (BLOCKS - degree + 1) * previous
            ) // (degree + 1)
            values[:] = [current, following]
    return answer


def even_subcode_weight(size: int, middle_internal: bool = False) -> int:
    assert size % 2 == 0
    if size <= T:
        return code_weight(size)
    if size == 16:
        return BLOCKS - code_weight(15, middle_internal)
    return BLOCKS - code_weight(V - size)


def griesmer(distance: int, dimension: int) -> int:
    return sum(
        (distance + (1 << power) - 1) // (1 << power)
        for power in range(dimension)
    )


def popcount(value: int) -> int:
    return value.bit_count()


def simplex_masks(dimension: int) -> tuple[int, ...]:
    points = tuple(range(1, 1 << dimension))
    masks = []
    for functional in range(1 << dimension):
        mask = 0
        for position, point in enumerate(points):
            if popcount(functional & point) % 2:
                mask |= 1 << position
        masks.append(mask)
    expected = 1 << (dimension - 1)
    assert Counter(map(popcount, masks)) == Counter(
        {0: 1, expected: (1 << dimension) - 1}
    )
    return tuple(masks)


def shortened_simplex_audit(dimension: int) -> dict[str, int]:
    """Shorten on the orthogonal of a simplex on 2^m-1 points.

    All words of the even point-subcode have even subset size.  Its only
    undetermined Fourier value occurs at size 16: when the complementary
    15-set is a block, that Fourier value increases by 2^15 and the
    punctured word weight decreases.  We therefore treat every size-16
    translate as internal.  The reported minimum is a rigorous lower
    bound, with equality asserted only when a minimizing coset has no
    size-16 translate.
    """
    masks = simplex_masks(dimension)
    support_size = (1 << dimension) - 1
    outside_size = V - support_size
    subgroup = set(masks)
    subgroup_fourier_sum = sum(
        fourier_value(popcount(mask))
        for mask in masks
    )
    length = subgroup_fourier_sum // len(masks)

    minimum: int | None = None
    external_minimum: int | None = None
    uncertain_at_minimum = False
    for inside_mask in range(1 << support_size):
        inside_size = popcount(inside_mask)
        for outside_weight in range(outside_size + 1):
            if (inside_size + outside_weight) % 2:
                continue
            if outside_weight == 0 and inside_mask in subgroup:
                continue
            translated_sum = 0
            external_translated_sum = 0
            uncertain = False
            for mask in masks:
                size = popcount(inside_mask ^ mask) + outside_weight
                external_value = fourier_value(size)
                external_translated_sum += external_value
                if size == K + 1:
                    uncertain = True
                    translated_sum += fourier_value(
                        size, internal_middle=True
                    )
                else:
                    translated_sum += external_value
            weight = (
                subgroup_fourier_sum - translated_sum
            ) // (2 * len(masks))
            external_weight = (
                subgroup_fourier_sum - external_translated_sum
            ) // (2 * len(masks))
            if (
                external_minimum is None
                or external_weight < external_minimum
            ):
                external_minimum = external_weight
            if minimum is None or weight < minimum:
                minimum = weight
                uncertain_at_minimum = uncertain
            elif weight == minimum:
                uncertain_at_minimum &= uncertain

    assert minimum is not None
    assert external_minimum is not None
    assert minimum > 0
    quotient_dimension = 30 - dimension
    return {
        "simplex_dimension": dimension,
        "simplex_support": support_size,
        "length": length,
        "minimum_lower_bound": minimum,
        "minimum_upper_bound": external_minimum,
        "minimum_is_forced": int(not uncertain_at_minimum),
        "quotient_dimension": quotient_dimension,
        "griesmer": griesmer(minimum, quotient_dimension),
        "griesmer_slack": (
            length - griesmer(minimum, quotient_dimension)
        ),
    }


def main() -> None:
    assert BLOCKS == 17_678_835
    assert LAMBDA == (
        17_678_835,
        8_554_275,
        3_991_995,
        1_789_515,
        766_935,
        312_455,
        120_175,
        43_263,
        14_421,
        4_389,
        1_197,
        285,
        57,
        9,
        1,
    )

    distribution = forced_weight_distribution()
    dual = krawtchouk_coefficients(distribution, 250)
    assert dual[:8] == [
        1,
        0,
        0,
        0,
        3_793_226_637_448_341_180,
        0,
        39_490_202_682_224_904_419_269_612_470_360,
        0,
    ]

    even_weights = [
        even_subcode_weight(size, internal)
        for size in range(2, V, 2)
        for internal in ((False, True) if size == 16 else (False,))
    ]
    minimum = min(even_weights)
    assert minimum == 8_809_920
    initial_griesmer = griesmer(minimum, 30)
    assert initial_griesmer == 17_619_853

    print(f"blocks={BLOCKS}")
    print(f"forced_primal_weight_support={len(distribution)}")
    print("macwilliams_coefficients_0_through_250=PASS")
    print(
        "even_subcode_parameters="
        f"[{BLOCKS},30,{minimum}]"
    )
    print(
        "initial_griesmer="
        f"{initial_griesmer}, slack={BLOCKS - initial_griesmer}"
    )
    for dimension in (2, 3, 4):
        result = shortened_simplex_audit(dimension)
        print(f"simplex_shortening_m{dimension}={result}")
    print("S(14,15,31) point-incidence code exploration: PASS")


if __name__ == "__main__":
    main()
